### PR TITLE
563- Custom file conflict changes added

### PR DESCRIPTION
**Pull request by TSI-sangramdesai**
Description:-
This PR is for release25
File conflicts you can cause if you upload twice a bunch of files in the same directory.
Build a small pre-dialog for quick decisions before the complex dialog of Nextcloud will appear
Here we shown custom file conflict dialog instead of Nextcloud dialog. 
Add below buttons for actions 
    1. Cancel
    2. Keep both files 
    3. Replace file

### CODE REVIEW

**Comment by tsdicloud** [comment]
Too big changes of core. Needs redesign first.

**Comment by tsdicloud** [comment]
It has to start with the master change first, and then a backport derived from there. Read the new delivery concept.

**Comment by TSI-sangramdesai** [comment]
Will work accordingly comments

**Comment by TSI-sangramdesai** [comment]
Closing this PR . Below PRs generated 
Master PR:- https://github.com/nextmcloud/server/pull/225
Back port 25 PR:- https://github.com/nextmcloud/server/pull/228

**Pull request closed without merging**
