### PR TITLE
127-file multiselection action

### PR DESCRIPTION
**Pull request by TSI-kavitasonawane**
This PR contains the following changes:
**File action button behaviour changes:**

- We now show more single actions depending on the viewport size in the table header beginning from the first option in the dropdown.
- We add a new option called "Cancel" (ger: Abbrechen") which will remove any selection (just remove selection, not the files of course).
- We right align the Actions button.
- We will show every option in the action button dropdown. It doesnt matter which option is also shown in the table header.
- We add a new label called "All".
- on S: we hide the label "All" according to the screen design

### CODE REVIEW

**Comment by tsdicloud** [comment]
Please check whether javascript changes can be done non-invasive in a separate package to avoid change on NC standard

**Comment by tsdicloud** [comment]
Generated css checked in, but shouldn't

**Comment by TSI-kavitasonawane** [comment]
> Please check whether parts of the change ("multiselect") are useful to add to Nextcloud server upstream. If so, pls separate these common changes from Telekom specific layout changes in separate CR and upstream the common part as PR to Nextcloud.

We had already raised as PR for upstream to nextcloud but they have closed it ..
so still we need to try to upstream these feature changes ??
**PR link:** https://github.com/nextcloud/server/pull/28834

**Comment by TSI-kavitasonawane** [comment]
> Generated css checked in, but shouldn't

I am working on it.

**Comment by TSI-kavitasonawane** [comment]
I have renamed this branch with same changes to follow the new branch naming-conventions for new delivery model.
so hence raising new PR by closing this one.

New PR link - https://github.com/nextmcloud/server/pull/217

**Pull request closed without merging**
