### PR TITLE
731-Settings-Replace username with email address

### PR DESCRIPTION
**Pull request by TSI-kavitasonawane**
This PR contains the following changes:

Devices & Sessions page(Settings): Replace username with email address

### CODE REVIEW

**Comment by tsdicloud** [comment]
Please explain in PR why this customisation is still needed or find a way to
upstream it as an option to Nextcloud server

**Comment by TSI-kavitasonawane** [comment]
> Please explain in PR why this customisation is still needed or find a way to upstream it as an option to Nextcloud server

Jens already confirmed with nextcloud and they rejected to upstream it.
so we need to keep this in customisation.

**Comment by tsdicloud** [comment]
Check whether the requirement is still correct as we now generally use display name, not email
as displayed user login.


Find all places in UI where this change gets relevant. If, after identification, we
need to keep the change, write safeguarding unittests for all occurrences.

**Comment by TSI-kavitasonawane** [comment]
I have renamed this branch with same changes to follow the new branch naming-conventions for new delivery model.
so hence raising new PR by closing this one.

New PR link - https://github.com/nextmcloud/server/pull/219

**Pull request closed without merging**
