### PR TITLE
127-file multiselection action

### PR DESCRIPTION
**Pull request by TSI-kavitasonawane**
This PR contains the following changes:
**File action button behaviour changes:**

We now show more single actions depending on the viewport size in the table header beginning from the first option in the dropdown.
We add a new option called "Cancel" (ger: Abbrechen") which will remove any selection (just remove selection, not the files of course).
We right align the Actions button.
We will show every option in the action button dropdown. It doesnt matter which option is also shown in the table header.
We add a new label called "All".
on S: we hide the label "All" according to the screen design

### CODE REVIEW

**Comment by TSI-kavitasonawane** [comment]
We had already raised as PR for upstream to nextcloud but they have closed it ..
so still we need to try to upstream these feature changes ??
PR link: https://github.com/nextcloud/server/pull/28834

**Comment by tsdicloud** [comment]
Still in acceptable many changed lines on core, though most of it is extension.
Waiting for a design that minimizes server core changes. Extensions can always be shifted to theme or nmc_sharing app.

**Comment by tsdicloud** [comment]
Would also recommend to re-read the new delivery model concept. An `accepted` label does not say anything about your change is only there to include code in server build. (renamed it to `build-ready` to make this absolutely clear.

ATM, I expect a complete restart for this change as nothing has improved compared to V24 according to the new "Minimized change" rules.

**Comment by tsdicloud** [comment]
Parts of the merge look specific to old grid layout.

**Comment by TSI-kavitasonawane** [comment]
We raised PR for upstream to nextcloud .
PR link: https://github.com/nextcloud/server/pull/38123

**Comment by tsdicloud** [comment]
I don't see that the finished PR is handled appropriately as the cancel code is still in the master patch.

As soon as Nextcloud contains an upstream patch, the refactoring steps are:
(1) Take out the aspect from the master patch or close the master patch PR if not needed anymore.
(2) Take the new code from Nextcloud and backport it for the older versions if needed.
       We will review the backport approach this week, but in general, a backport is a branch with the same name as the master branch but with a `-<version>` suffix. So, if your master patch name is `nmc/4711-my-pr-raise-branch`, then
       the backport name for V25 is like `nmc/4711-my-pr-raise-branch-25` (from the new build process, will be a change in the concept this week)
 (3) Test backport on older release.

I don't see any care for the https://github.com/nextcloud/server/pull/28834 yet.

**Comment by tsdicloud** [comment]
Overwrite of Nextcloud code, should be an extension as add-on functionality to Nextcloud standard.

**Pull request closed without merging**
